name: Enforce Semi-Linear History

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-linear-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: cytario/enforce-semi-linear-history@2d02ad4f23b50551ee334ba3416da5461cdbd050 # v1
